baseURL = "https://example.com/"
languageCode = "en-gb"
title = "Hugo Theme - Prav"
theme = "hugo-theme-prav"

pygmentsCodeFences = "true"
pygmentsStyle = "perldoc"

# If you want to track using GA or use disqus for comments, uncomment the 
# following and add the correct values
#googleanalytics = ""
#disqusShortname = ""

# The settings below are used throughout the theme.
# Please update!
[params]
    title = "Bartholoblog"
    tagline = "Under Construction"
    author = "Matt Bartholomew"
    authorImgPath = "/img/portrait.jpg"
    authorBlurb = "Matt Bartholomew is a Data Scientist from Austin Texas"

# If you do not want a social icon, just comment it out
# Please update the example values!
[social]
    email = "mailto:bartholomatt@gmail.com"
    #facebook = "https://www.facebook.com/example"
    twitter = "http://twitter.com/bartholomatt"
    #medium = "https://www.medium.com/@example"
    github = "https://github.com/bartholomatt"
    linkedin = "http://linkedin.com/in/bartholomatt"


# Set unsafe mode to allow markdownify to work with goldmark
#Â This is important. Please do not delete. It is used to re-render markdown
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
